chore(publish): V0.22.0 (#110)
Branch protection caused direct push to `refs/head/main` to be blocked

```
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 32 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 1.98 KiB | 1.98 MiB/s, done.
Total 7 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: 
remote: - Changes must be made through a pull request.
To github.com:foundry-rs/block-explorers.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'github.com:foundry-rs/block-explorers.git'
```